export const HeadsData = [
  {
    player: 1,
    id: 1,
    image: "heads.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 1,
    id: 2,
    image: "heads.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 1,
    id: 3,
    image: "heads.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 1,
    id: 4,
    image: "heads.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 1,
    id: 5,
    image: "heads.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 1,
    id: 6,
    image: "heads.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 1,
    id: 7,
    image: "heads.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 1,
    id: 8,
    image: "heads.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 1,
    id: 9,
    image: "heads.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 1,
    id: 10,
    image: "heads.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 1,
    id: 11,
    image: "heads.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 1,
    id: 12,
    image: "heads.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 1,
    id: 13,
    image: "heads.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 1,
    id: 14,
    image: "heads.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 1,
    id: 15,
    image: "heads.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 1,
    id: 16,
    image: "heads.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 1,
    id: 17,
    image: "heads.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 1,
    id: 18,
    image: "heads.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 1,
    id: 19,
    image: "heads.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 1,
    id: 20,
    image: "heads.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 2,
    id: 21,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 2,
    id: 22,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 2,
    id: 23,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 2,
    id: 24,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 2,
    id: 25,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 2,
    id: 26,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 2,
    id: 27,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 2,
    id: 28,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 2,
    id: 29,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 2,
    id: 30,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 2,
    id: 31,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 2,
    id: 32,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 2,
    id: 33,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 2,
    id: 34,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 2,
    id: 35,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 2,
    id: 36,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 2,
    id: 37,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 2,
    id: 38,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 2,
    id: 39,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 2,
    id: 40,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 3,
    id: 41,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 3,
    id: 42,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 3,
    id: 43,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 3,
    id: 44,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 3,
    id: 45,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 3,
    id: 46,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 3,
    id: 47,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 3,
    id: 48,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 3,
    id: 49,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 3,
    id: 50,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 3,
    id: 51,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 3,
    id: 52,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 3,
    id: 53,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 3,
    id: 54,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 3,
    id: 55,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 3,
    id: 56,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 3,
    id: 57,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 3,
    id: 58,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 3,
    id: 59,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
  {
    player: 3,
    id: 60,
    image: "empty.jpg",
    background: false,
    beenflipped: false,
    beenshipped: false,
    beendelivered: false,
  },
];
